# Generated by Django 5.1.4 on 2024-12-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='image',
            field=models.ImageField(default='static/images/backgroung.jpg', upload_to='bikeimages'),
        ),
    ]
