# Generated by Django 5.1.5 on 2025-01-28 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_alter_user_role_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructorprofile',
            old_name='Owner',
            new_name='owner',
        ),
    ]
